pipeline {
    agent {
        label "devops"
    }
    tools {
        maven 'mvn'
    }
    stages{
        stage("Clean Workspace") { 
            steps {
                cleanWs()
            }
        }
        stage("Code Checkout"){
          steps{ 
            git url:"https://github.com/prateekkumawat/jenkinsproject330.git", branch: "nexus3"
          }
        }
        
        stage("Maven package build"){
            steps{
                sh 'mvn clean package'
            }
        }
     
       stage("Artifacts Upload"){
            steps{
                nexusArtifactUploader (
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: 'http://18.61.183.118:8081/repository/maven-releases/',
                    groupId: 'backend.hobbiebackend',
                    version: 2.4.2,
                    repository: 'nexus-releases',
                    credentialsId: 'nexuscreds',
                    artifacts: [
                        [artifactId: hobbie-backend,
                        classifier: '',
                        file: 'hobbie-backend' + 0.0.1-SNAPSHOT + '.jar',
                        type: 'jar']
                    ]    
                )    
            }
        }

        
    }
}