pipeline {
    agent {
        label "devops"
    }
    tools {
        mvn 'mvn'
    }
    stages{
        stage("Clean Workspace") { 
            steps {
                cleanWs()
            }
        }
        stage("Code Checkout"){
          steps{ 
            git url:"https://github.com/prateekkumawat/jenkinsproject330.git", branch: "nexus"
          }
        }
        
        stage("Maven package build"){
            steps{
                sh 'mvn clean package'
            }
        }
     
       stage("Artifacts Upload"){
            steps{
                nexusArtifactUploader (
                    credentialsId: 'nexuscreds',
                    artifacts: [
                        [artifactId: myca-commons,
                        classifier: '',
                        file: 'myca-common' + version + '.jar',
                        type: 'jar']
                    ]    
                )    
            }
        }

        
    }
}